BUGS-6304 Prepare EDI 204 counts after validation trimming
cloudlogistics/baldr pull request #26
Opened 2018-05-07 19:53 UTC by Cardds

When the validations run with the 'truncate' option on, the transaction
ST values are not updated with the correct number of segments. By
calling `prepare!` when the truncation option has been turned on, it
updates the particular segment (transaction, envelope, or otherwise)
with the new number.

Dev note: it appears that some of the test case data that is listed as
being valid is not valid, e.g. some ST01 values are either nonexistent
when they are required for the particular format, or they have
inaccurate values.

2018-05-07 20:02 UTC, scottkf requested changes
@Cardds can you please add a corresponding spec for this?

2018-05-08 13:29 UTC, Cardds commented
@scottkf Three additional specs to check this parameter and associated functionality.

Note that this is also addresses BUGS-6453 with a hotfix in a separate commit; more work may need to be done on BUGS-6453, but this should lower the priority.

2018-05-08 14:14 UTC, scottkf requested changes
@Cardds bump the version and adjust in the broker please

2018-05-08 14:19 UTC, Cardds commented
@scottkf Patch # incremented in version.

2018-05-08 14:20 UTC, scottkf approved these changes
@Cardds good to merge

2018-05-08 14:27 UTC, merged